name: fints_client
description: A dart based FinTS Client 
version: 0.0.1
author: Stephan Vedder <stephan.vedder@gmail.com>
homepage: https://github.com/feliwir/fints_client

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  iban: ^0.1.1
  validators: ^2.0.0+1
  intl: ^0.16.0
  cryptoutils: ^0.4.0

dev_dependencies:
  test: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec